# Configuration for the typos spell checker utility (<https://github.com/crate-ci/typos>).

[files]
extend-exclude = [
    "*.drawio.xml"
]

[default.extend-words]
Rela = "Rela"
grup = "grup"

[default.extend-identifiers]
typ = "typ"
